default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["WEB_DB_POOL"] || 5 %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["WEB_DB_POOL"] || 5 %>
  timeout: 5000
  database: <%= ENV["DATABASE_NAME_DEVELOPMENT"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
test:
  <<: *default
  database: <%= ENV["DATABASE_NAME_TEST"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>

staging:
  <<: *default
  database: <%= ENV["STAGING_DB_DATABASE"] %>
  username: <%= ENV["STAGING_DB_USERNAME"] %>
  password: <%= ENV["STAGING_DB_PASSWORD"] %>

production:
  <<: *default
  database: localyzeapp
  username: <%= ENV["PRODUCTION_DB_NAME"] %>
  password: <%= ENV["PRODUCTION_DB_PASSWORD"] %>

